apps/projects/urls.py
from django.urls import path

from apps.projects.views import ProjectDetailView, ProjectsListView

urlpatterns = [
    path("projects/", ProjectsListView.as_view(), name="projects_list"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="projects_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

DEBUG = settings.DEBUG
MEDIA_URL = settings.MEDIA_URL
MEDIA_ROOT = settings.MEDIA_ROOT

handler400 = "apps.main_page.views.bad_request"
handler403 = "apps.main_page.views.permission_denied"
handler404 = "apps.main_page.views.page_not_found"
handler500 = "apps.main_page.views.server_error"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.main_page.urls")),
    path("", include("apps.club.urls")),
    path("", include("apps.services.urls")),
    path("", include("apps.news.urls")),
    path("", include("apps.projects.urls")),
    path("", include("apps.equipment.urls")),
    path("", include("apps.questions.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

apps/projects/models.py
from ckeditor.fields import RichTextField
from django.db import models

from config.utils.slugify import slugify


class ProjectCategory(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Название категории",
    )
    slug = models.SlugField(
        max_length=70,
        blank=True,
        verbose_name="URL категории",
        help_text="Если оставить пустым, заполнится транслитом название категории",
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Категория проектов"
        verbose_name_plural = "Категории проектов"

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(
        max_length=200,
        verbose_name="Название проекта",
    )
    title = models.CharField(
        max_length=500,
        verbose_name="Краткое описание",
    )
    text = RichTextField(
        verbose_name="Основной текст",
    )
    category = models.ForeignKey(
        ProjectCategory,
        on_delete=models.CASCADE,
        verbose_name="Категории",
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = [
            "name",
        ]
        verbose_name = "Проект"
        verbose_name_plural = "Проекты"
        constraints = [
            models.UniqueConstraint(
                fields=["name", "title"],
                name="unique_name_for_title",
            ),
        ]


class ProjectImage(models.Model):
    image = models.ImageField(
        upload_to="images/projects/detail/",
        verbose_name="Изображение проекта",
    )
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        verbose_name="Проект",
    )

    class Meta:
        verbose_name = "Изображение проекта"
        verbose_name_plural = "Изображения проекта"

    def __str__(self):
        image_name = (self.image.name).split("/")[-1]
        return image_name

apps/projects/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from apps.projects.models import Project, ProjectImage


class ProjectDetailView(DetailView):

    model = Project
    template_name = "projects/project_detail.html"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context["project_images"] = ProjectImage.objects.filter(project=self.object)
        return self.render_to_response(context)


class ProjectsListView(ListView):

    model = Project
    template_name = "projects/project_list.html"

templates/projects/project_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ object.name }}{% endblock %}
{% block content %}
<section>
</section>
<section id="portfolio-details" class="portfolio-details section-bg">
  <div class="container">
    <div class="row gy-4">
      <div class="col-md-6" >
        <div class="portfolio-details-slider swiper">
          <div class="swiper-wrapper align-items-center">
            {% for image in project_images.all %}
            <div class="swiper-slide">
              <a href="{{ image.image.url }}" data-gallery="portfolioGallery"
                class="portfolio-lightbox"><img src="{{ image.image.url }}" style="max-width: 100%; max-height: auto; object-position: center;" alt=""></a>
            </div>
            {% endfor %}
          </div>
          <div class="swiper-button-prev" style="color: #d3d3d342"></div>
          <div class="swiper-button-next" style="color: #d3d3d342"></div>
          <div class="swiper-pagination"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="portfolio-description">
          <h2>{{ object.title }}</h2>
          <p>{{ object.text|safe }}</p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}
{% block extrascripts %}
<script>
  var swiper = new Swiper('.swiper', {
      direction: 'horizontal',
      loop: true,
      centeredSlides: true,
      autoplay: true,
      simulateTouch:true,

      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
</script>
{% endblock %}

templates/projects/project_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Наши проекты{% endblock %}

{% block content %}
{% load tags %}
<section></section>
<section id="portfolio" class="portfolio section-bg">
  <div class="container">

    <div class="section-title" data-aos="fade-up">
      <h2>Наши проекты</h2>
      <p>За десятилетия работы мы создали немало удивительных проектов</p>
    </div>

    <div class="row" data-aos="fade-up" data-aos-delay="200">
      <div class="col-lg-12 d-flex justify-content-center">
        <ul id="portfolio-flters">
          {% get_project_categories as categories %}
          <li data-filter="*" class="filter-active">Все</li>
          {% for category in categories %}
          <li data-filter=".filter-{{ category.slug }}">{{ category.name }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>

    <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="300">
      {% for project_item in object_list %}
      <div class="col-lg-4 col-md-6 portfolio-item filter-{{ project_item.category.slug }}">
        <div class="portfolio-wrap">
          <img src="{{ project_item.projectimage_set.first.image.url }}" class="img-fluid" alt="">
          <div class="portfolio-info">
            <a href="{% url 'projects_detail' project_item.id %}"><h4>{{ project_item.name }}</h4></a>
            <a href="{% url 'projects_detail' project_item.id %}"><p>{{ project_item.title }}</p></a>
            <div class="portfolio-links">
              <a href="{{ project_item.projectimage_set.first.image.url }}" data-gallery="portfolioGallery"
                class="portfolio-lightbox" title="{{ project_item.name }}"><i class="bx bx-move"></i></a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}