apps/equipment/urls.py
from django.urls import include, path

from apps.equipment.views import (
    EquipmentBrendDetailView,
    EquipmentCategoryDetailView,
    EquipmentCategoryListView,
    EquipmentItemDetailView,
    EquipmentItemResultsView,
    EquipmentSubCategoryDetailView,
    add_request,
)

equipments_urls = [
    path(
        "",
        EquipmentCategoryListView.as_view(),
        name="equipments",
    ),
    path("search-results/", EquipmentItemResultsView.as_view(), name="equip_search_results"),
    path(
        "<slug:category_slug>/",
        EquipmentCategoryDetailView.as_view(),
        name="equipment-categories",
    ),
    path(
        "<slug:category_slug>/<slug:subcategory_slug>/",
        EquipmentSubCategoryDetailView.as_view(),
        name="equipment-subcategories",
    ),
    path(
        "<slug:category_slug>/<slug:subcategory_slug>/<slug:brend_slug>/",
        EquipmentBrendDetailView.as_view(),
        name="equipment-brends",
    ),
    path(
        "<slug:category_slug>/<slug:subcategory_slug>/<slug:brend_slug>/<int:pk>/",
        EquipmentItemDetailView.as_view(),
        name="equipment-item",
    ),
]

urlpatterns = [
    path("equipment/", include(equipments_urls)),
    path("ask_request/", add_request, name="ask_request"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

DEBUG = settings.DEBUG
MEDIA_URL = settings.MEDIA_URL
MEDIA_ROOT = settings.MEDIA_ROOT

handler400 = "apps.main_page.views.bad_request"
handler403 = "apps.main_page.views.permission_denied"
handler404 = "apps.main_page.views.page_not_found"
handler500 = "apps.main_page.views.server_error"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.main_page.urls")),
    path("", include("apps.club.urls")),
    path("", include("apps.services.urls")),
    path("", include("apps.news.urls")),
    path("", include("apps.projects.urls")),
    path("", include("apps.equipment.urls")),
    path("", include("apps.questions.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

apps/equipment/models.py
from ckeditor.fields import RichTextField
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from config.utils.slugify import slugify
from config.utils.youtube_links import get_current_link


class EquipmentCategory(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Название категории",
    )
    category_slug = models.SlugField(
        max_length=70,
        blank=True,
        verbose_name="URL категории",
        help_text="Если оставить пустым, заполнится транслитом название категории",
    )
    image = models.ImageField(
        upload_to="images/equipment-category",
        verbose_name="Изображение категории",
        help_text="Для лучшего отображения должно быть равное соотношение сторон",
    )

    def save(self, *args, **kwargs):
        if not self.category_slug:
            self.category_slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Категория оборудования"
        verbose_name_plural = "Категории оборудования"

    def __str__(self):
        return self.name


class EquipmentSubCategory(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Название категории",
    )
    subcategory_slug = models.SlugField(
        max_length=70,
        blank=True,
        verbose_name="URL категории",
        help_text="Если оставить пустым, заполнится транслитом название категории",
    )
    category = models.ForeignKey(
        EquipmentCategory,
        on_delete=models.CASCADE,
        related_name="categories",
        verbose_name="Категория",
    )
    image = models.ImageField(
        upload_to="images/equipment-category/subcategory",
        verbose_name="Изображение подкатегории",
        help_text="Для лучшего отображения должно быть равное соотношение сторон",
    )

    def save(self, *args, **kwargs):
        if not self.subcategory_slug:
            self.subcategory_slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["name"]
        verbose_name = "Подкатегория оборудования"
        verbose_name_plural = "Подкатегории оборудования"
        constraints = [
            models.UniqueConstraint(
                fields=["name", "category"],
                name="unique_subcategory_for_category",
            ),
        ]

    def __str__(self):
        return self.name


class EquipmentBrend(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Название бренда",
    )
    brend_slug = models.SlugField(
        max_length=70,
        blank=True,
        verbose_name="URL бренда",
        help_text="Если оставить пустым, заполнится транслитом название категории",
    )
    subcategory = models.ForeignKey(
        EquipmentSubCategory,
        on_delete=models.CASCADE,
        related_name="subcategories",
        verbose_name="Подкатегория",
    )
    image = models.ImageField(
        upload_to="images/equipment-category/brend",
        verbose_name="Изображение бренда",
        help_text="Для лучшего отображения должно быть равное соотношение сторон",
    )

    def save(self, *args, **kwargs):
        if not self.brend_slug:
            self.brend_slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Бренд оборудования"
        verbose_name_plural = "Бренды оборудования"

    def __str__(self):
        return self.name


class EquipmentItemImage(models.Model):
    image = models.ImageField(
        upload_to="images/equipment-category/items/images",
        verbose_name="Изображения в карусели единицы оборудования",
        help_text="Для лучшего отображения должно быть равное соотношение сторон",
    )
    equipment = models.ForeignKey(
        "EquipmentItem",
        on_delete=models.CASCADE,
        verbose_name="Оборудование",
    )
    my_order = models.PositiveIntegerField(
        default=0,
        blank=False,
        null=False,
        verbose_name="Порядок отображения",
    )

    class Meta:
        verbose_name = "Изображение единицы оборудования"
        verbose_name_plural = "Изображения единицы оборудования"
        ordering = ["my_order"]

    def __str__(self):
        image_name = (self.image.name).split("/")[-1]
        return image_name

    def clean(self):
        height = 400
        width = 400
        if self.image.height < height or self.image.width < width:
            raise ValidationError(f"Размеры изображения должны быть не менее {height}x{width}")


class EquipmentItemDocument(models.Model):
    document = models.FileField(
        upload_to="images/equipment-category/items/documents",
        verbose_name="Документ во вложении",
    )
    equipment = models.ForeignKey(
        "EquipmentItem",
        on_delete=models.CASCADE,
        verbose_name="Оборудование",
    )
    my_order = models.PositiveIntegerField(
        default=0,
        blank=False,
        null=False,
        verbose_name="Порядок отображения",
    )

    class Meta:
        verbose_name = "Документ единицы оборудования"
        verbose_name_plural = "Документы единицы оборудования"
        ordering = ["my_order"]

    def __str__(self):
        document_name = (self.document.name).split("/")[-1]
        return document_name

    def name(self):
        return (self.document.name).split("/")[-1]


class EquipmentItemYoutubeVideoUrl(models.Model):
    video_url = models.CharField(
        max_length=150,
        verbose_name="Ссылка на видео YouTube",
    )
    equipment = models.ForeignKey(
        "EquipmentItem",
        on_delete=models.CASCADE,
        verbose_name="Оборудование",
    )
    my_order = models.PositiveIntegerField(
        default=0,
        blank=False,
        null=False,
        verbose_name="Порядок отображения",
    )

    class Meta:
        verbose_name = "Ссылка на видео YouTube"
        verbose_name_plural = "Ссылки на видео YouTube"
        ordering = ["my_order"]

    def __str__(self):
        self.video_url

    def save(self, *args, **kwargs):
        self.video_url = get_current_link(self.video_url)
        super().save(*args, **kwargs)


class EquipmentItem(models.Model):
    name = models.CharField(
        max_length=200,
        verbose_name="Название оборудования",
    )
    title = models.CharField(
        max_length=500,
        blank=True,
        verbose_name="Краткое описание",
    )
    tech_data = RichTextField(
        verbose_name="Технические характеристики",
        blank=True,
    )
    subcategory = models.ForeignKey(
        EquipmentSubCategory,
        on_delete=models.CASCADE,
        verbose_name="Подкатегория",
    )
    brend = models.ForeignKey(
        EquipmentBrend,
        on_delete=models.CASCADE,
        verbose_name="Бренд",
    )
    my_order = models.PositiveIntegerField(
        default=0,
        blank=False,
        null=False,
        verbose_name="Порядок отображения",
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["my_order"]
        verbose_name = "Оборудование"
        verbose_name_plural = "Оборудование"
        constraints = [
            models.UniqueConstraint(
                fields=["name", "title"],
                name="unique_name_for_title_equipment",
            ),
        ]


class LastViewedEquipmentItem(models.Model):
    session = models.CharField(
        max_length=200,
        verbose_name="Ключ сессии",
    )
    equipment_item = models.ForeignKey(
        EquipmentItem,
        on_delete=models.CASCADE,
        verbose_name="Оборудование",
    )


class EquipmentRequest(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Ваше имя",
    )
    email = models.EmailField(
        max_length=150,
        verbose_name="Email",
    )
    phone_number = PhoneNumberField(verbose_name="Телефон", blank=True, help_text="Необязательно")
    text = models.TextField(
        verbose_name="Ваш запрос",
        validators=[MinLengthValidator(10)],
    )

    class Meta:
        verbose_name = "Запрос оборудования"
        verbose_name_plural = "Запросы оборудования"

    def __str__(self):
        return self.name

apps/equipment/forms.py
from django import forms

from apps.equipment.models import EquipmentRequest


class EquipmentRequestModelForm(forms.ModelForm):
    class Meta:
        model = EquipmentRequest
        fields = ["name", "email", "phone_number", "text"]

apps/equipment/views.py
import json

from django.conf import settings
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView, MultipleObjectMixin

from apps.equipment.forms import EquipmentRequestModelForm
from apps.equipment.models import (
    EquipmentBrend,
    EquipmentCategory,
    EquipmentItem,
    EquipmentSubCategory,
    LastViewedEquipmentItem,
)


class EquipmentCategoryListView(ListView):

    model = EquipmentCategory
    template_name = "equipment/equipments.html"


class EquipmentCategoryDetailView(DetailView):

    model = EquipmentCategory
    slug_field = "category_slug"
    slug_url_kwarg = "category_slug"
    template_name = "equipment/equipments-categories.html"

    def get_queryset(self):
        return EquipmentCategory.objects.filter(category_slug=self.kwargs["category_slug"]).values("name")

    def get_context_data(self, **kwargs):
        self.object["category_slug"] = self.kwargs["category_slug"]
        context = {}
        super().get_context_data()
        context["subcategories"] = EquipmentSubCategory.objects.filter(
            category__category_slug=self.kwargs["category_slug"]
        )
        return super().get_context_data(**context)


class EquipmentSubCategoryDetailView(DetailView):

    model = EquipmentSubCategory
    slug_field = "subcategory_slug"
    slug_url_kwarg = "subcategory_slug"
    template_name = "equipment/equipments-subcategories.html"

    def get_queryset(self):
        return EquipmentSubCategory.objects.filter(subcategory_slug=self.kwargs["subcategory_slug"]).all()

    def get_context_data(self, **kwargs):
        context = {}
        super().get_context_data()
        context["brends"] = EquipmentBrend.objects.filter(subcategory__subcategory_slug=self.kwargs["subcategory_slug"])
        return super().get_context_data(**context)


class EquipmentBrendDetailView(MultipleObjectMixin, DetailView):

    model = EquipmentBrend
    slug_field = "brend_slug"
    slug_url_kwarg = "brend_slug"
    template_name = "equipment/equipments-brends.html"
    paginate_by = 6

    def get_queryset(self):
        return EquipmentBrend.objects.filter(brend_slug=self.kwargs["brend_slug"]).all()

    def get_context_data(self, **kwargs):
        object_list = EquipmentItem.objects.filter(brend__brend_slug=self.kwargs["brend_slug"])
        context = super().get_context_data(object_list=object_list, **kwargs)
        return context


class EquipmentItemDetailView(DetailView):

    model = EquipmentItem
    template_name = "equipment/equipments-detail.html"

    def get_object(self):
        obj = super().get_object()
        if not self.request.session or not self.request.session.session_key:
            self.request.session.save()
        LastViewedEquipmentItem.objects.get_or_create(session=self.request.session.session_key, equipment_item=obj)
        last_viewed = LastViewedEquipmentItem.objects.filter(session=self.request.session.session_key)
        if last_viewed.count() > 5:
            last_viewed.first().delete()
        return obj


class EquipmentItemResultsView(ListView):
    model = EquipmentItem
    template_name = "equipment/equip_search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("search")
        search_vector = SearchVector("name", "title", "brend__name")
        search_query = SearchQuery(query)
        object_list = (
            EquipmentItem.objects.annotate(search=search_vector, rank=SearchRank(search_vector, search_query))
            .filter(search=search_query)
            .order_by("-rank")
        )
        return object_list


def add_request(request):
    if request.method == "POST":
        form = EquipmentRequestModelForm(request.POST)
        if form.is_valid():
            request_equipment = form.save()
            subject = f"Поступил запрос на оборудование от {form.data.get('name')} с rusjet.ru"
            msg_plain = render_to_string("equipment/email.txt", form.data)
            msg_html = render_to_string("equipment/email.html", form.data)
            send_mail(
                subject,
                msg_plain,
                settings.EMAIL_HOST_USER,
                [settings.DEFAULT_FROM_EMAIL],
                html_message=msg_html,
            )
            return HttpResponse(
                status=204, headers={"HX-Trigger": json.dumps({"showMessage": f"{request_equipment.name} added."})}
            )
    else:
        form = EquipmentRequestModelForm()
    return render(
        request,
        "equipment/create_request.html",
        {
            "form": form,
        },
    )

templates/equipment/create_request.html
{% load widget_tweaks %}
{% with WIDGET_ERROR_CLASS='is-invalid' %}
<form hx-post="{{ request.path }}" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title">Форма запроса</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <div class="mb-3">
      <label for="{{ form.name.id_for_label }}" class="form-label">Ваше имя</label>
      {% render_field form.name class="form-control" placeholder="Пожалуйста, представьтесь" %}
      <div class="invalid-feedback">{{ form.name.errors|first }}</div>
    </div>
    <div class="mb-3">
      <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
      {% render_field form.email class="form-control" placeholder="Укажите, чтобы связаться с Вами" %}
      <div class="invalid-feedback">{{ form.email.errors|first }}</div>
    </div>
    <div class="mb-3">
      <label for="{{ form.phone_number.id_for_label }}" class="form-label">Телефон</label >
      {% render_field form.phone_number class="form-control" placeholder="Необязательно" %}
      <div class="invalid-feedback">{{ form.phone_number.errors|first }}</div>
    </div>
    <div class="mb-3">
      <label for="{{ form.text.id_for_label }}" class="form-label">Ваш вопрос</label >
      {% render_field form.text class="form-control" placeholder="Укажите количество, так же можно указать необходимую периферию и комплектующие" %}
      <div class="invalid-feedback">{{ form.text.errors|first }}</div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" style="border-radius: 30px;" data-bs-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-primary" style="background: #3498db; border-color: #3498DB; border-radius: 30px;">Отправить</button>
  </div>
</form>
{% endwith %}

templates/equipment/email.html
<style>
    .message-content {
    max-width: 600px;
    margin: 30px auto;
    font-family: Helvetica, Arial, sans-serif;
    }
    .message-content div {
    padding-bottom: 10px;
    }
    .message-content img {
    max-width: 100%;
    height: auto;
    margin: 0 auto;
    }

    * {
    font-family: Helvetica, Arial, sans-serif;
    }

    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
    color: #333;
    }
    h1 {
    font-size: 32px;
    }
    h2 {
    font-size: 24px;
    }
    h3 {
    font-size: 18px;
    }

    p,
    li,
    ul,
    ol,
    div {
    font-size: 18px;
    line-height: 1.5em;
    font-family: Helvetica, Arial, sans-serif;
    color: #333333;
    }

    p *,
    li * {
    color: inherit;
    font-family: inherit;
    font-size: inherit;
    }

    p,
    ul,
    ol {
    margin-bottom: 1em;
    }

    blockquote {
    border-left: solid 5px #aaa;
    margin: 20px 0px;
    padding: 15px 30px;
    font-size: 20px;
    line-height: 1.5em;
    color: #444;
    font-family: Helvetica, Arial, sans-serif;
    }

    a {
    text-decoration: none;
    font-size: 15px;
    border-bottom: 1px dotted #0875c1;
    color: #0875c1;
    }

    a:hover {
    color: #1b8ede;
    border-bottom-color: #1b8ede;
    }

    .button {
    border: none;
    background: #777;
    color: #fff;
    padding: 10px;
    display: inline-block;
    margin: 10px 0px;
    font-family: Helvetica, Arial, sans-serif;
    -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    border-radius: 3px;
    }

    .button:hover {
    color: #fff;
    background: #666;
    }

    .footer {
    border-top: 1px dotted #888;
    padding: 20px 0px;
    font-family: Helvetica, Arial, sans-serif;
    color: #aaa;
    font-size: 12px;
    }

    .social-links {
    margin-bottom: 10px;
    padding: 0px;
    }
    .social-links a {
    text-align: center;
    padding: 5px;
    border: none;
    }
    </style>
    <div class="message-content">
    <h3>{{ name }} интересуется:</h3>
    <p>{{ text }}</p>

    <div class="footer">
    <p>Контакты для связи с {{ name }}:</p>
    <a href="mailto:{{ email }}">{{ email }}</a> |
    <a href="tel:{{ phone_number }}">{{ phone_number }}</a>
    </div>
    </div>

templates/equipment/equip_search_results.html
{% extends "equipment/equipment-base.html" %}
{% load static %}

{% block title %}Результаты поиска{% endblock %}

{% block breadcrumbs %}Результаты поиска{% endblock %}

{% block shop %}
{% for object in object_list %}
  <div class="col-auto mb-2">
    <div class="shop-card"
      style="background: url('{{ object.equipmentitemimage_set.first.image.url }}');">
      <div class="shop-card-category">{{ object.name }}</div>
      <div class="shop-card-description">{{ object.brend.name }}</div>
      <a class="shop-card-link" href="{% url 'equipment-item' category_slug=object.brend.subcategory.category.category_slug subcategory_slug=object.brend.subcategory.subcategory_slug brend_slug=object.brend.brend_slug pk=object.pk %}#details"></a>
    </div>
  </div>
{% empty %}
  <a>К сожалению, ничего не нашлось...</a>
{% endfor %}
{% endblock %}

templates/equipment/equipments-brends.html
{% extends "equipment/equipment-base.html" %}
{% load static %}

{% block title %}{{ object.name }}{% endblock %}

{% block breadcrumbs %}<a href="{% url 'equipments' %}">Оборудование > </a><a href="{% url 'equipment-categories' category_slug=object.subcategory.category.category_slug %}">{{ object.subcategory.category.name }} > </a><a href="{% url 'equipment-subcategories' category_slug=object.subcategory.category.category_slug subcategory_slug=object.subcategory.subcategory_slug %}#content">{{object.subcategory.name }} > </a><a href="{% url 'equipment-brends' category_slug=object.subcategory.category.category_slug subcategory_slug=object.subcategory.subcategory_slug brend_slug=object.brend_slug %}">{{object.name }} </a>{% endblock %}


{% block shop %}
{% for object in object_list %}
  <div class="col-auto mb-2">
    <div class="shop-card"
      style="background: url('{{ object.equipmentitemimage_set.first.image.url }}');">
      <div class="shop-card-category">{{ object.name }}</div>
      <a class="shop-card-link" href="{% url 'equipment-item' category_slug=object.brend.subcategory.category.category_slug subcategory_slug=object.brend.subcategory.subcategory_slug brend_slug=object.brend.brend_slug pk=object.pk %}#details"></a>
    </div>
  </div>
{% endfor %}
{% endblock %}

templates/equipment/equipments-detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style>
<section id="breadcrumbs" class="breadcrumbs">
  <div class="container">
      <div class="d-flex justify-content-between align-items-center">
        <h2><a href="{% url 'equipments' %}">Оборудование > </a><a href="{% url 'equipment-categories' category_slug=object.brend.subcategory.category.category_slug %}">{{ object.brend.subcategory.category.name }} > </a><a href="{% url 'equipment-subcategories' category_slug=object.brend.subcategory.category.category_slug subcategory_slug=object.brend.subcategory.subcategory_slug %}">{{object.brend.subcategory.name }} > </a><a href="{% url 'equipment-brends' category_slug=object.brend.subcategory.category.category_slug subcategory_slug=object.brend.subcategory.subcategory_slug brend_slug=object.brend.brend_slug %}">{{object.brend.name }} </a><a href="{% url 'equipment-item' category_slug=object.brend.subcategory.category.category_slug subcategory_slug=object.brend.subcategory.subcategory_slug brend_slug=object.brend.brend_slug pk=object.pk %}#details">{{ object.name }}</a></h2>
      </div>
  </div>
</section>



<section id="shop" class="shop section-bg">
    <div class="container" data-aos="fade-up" data-aos-duration="300">
      <div class="row">
        <div class="col-lg-3 col-md-4 col-sm-6">
          {% include 'equipment/includes/sidebar.html' %}
        </div>

        <div class="col-lg-9 col-md-8 col-sm-6" >
          <section id="details">
            <div class="row">
                <div class="col-lg-5 col-md-9 col-sm-12" >
                  <div class="portfolio-details-slider swiper">
                    <div class="swiper-wrapper">
                      {% for image in object.equipmentitemimage_set.all %}
                      <div class="swiper-slide">
                        <a href="{{ image.image.url }}" data-gallery="portfolioGallery" class="portfolio-lightbox">
                          <img src="{{ image.image.url }}" style="max-width: 400px; max-height: auto; object-position: center;" alt="">
                        </a>
                      </div>
                      {% endfor %}
                    </div>
                    <div class="swiper-button-prev" style="color: #d3d3d342"></div>
                    <div class="swiper-button-next" style="color: #d3d3d342"></div>
                  </div>
                </div>


                <div class="col-lg-7 col-md-12 col-sm-12 gy-3">
                  <div class="shop-detail-description">
                    <h2>{{ object.name }}</h2>
                    {% if object.title %}
                    <p>{{ object.title }}</p>
                    {% endif %}
                  </div>
                  <div class="row">
                    <div class="col text-center p-3">
                      <a hx-get="{% url 'ask_request' %}" hx-target="#dialog" class="getstarted scrollto" type="button" name="button">Связаться</a>
                    </div>
                  </div>
                </div>

                <div class="col-lg-10 col-md-12 col-sm-12 gy-3">
                  
                  <ul class="nav nav-tabs mb-4" id="myTab" role="tablist">
                    {% if object.tech_data %}
                    <li class="nav-item" role="presentation">
                      <button class="nav-link active" style="color: #3598db;" id="technical-tab" data-bs-toggle="tab" data-bs-target="#technical" type="button" role="tab" aria-controls="technical" aria-selected="true">Характеристики</button>
                    </li>
                    {% endif %}
                    {% if object.equipmentitemdocument_set.first %}
                    <li class="nav-item" role="presentation">
                      <button class="nav-link" style="color: #3598db" id="documentation-tab" data-bs-toggle="tab" data-bs-target="#documentation" type="button" role="tab" aria-controls="documentation" aria-selected="false">Загрузки</button>
                    </li>
                    {% endif %}
                    {% if object.equipmentitemyoutubevideourl_set.first %}
                    <li class="nav-item" role="presentation">
                      <button class="nav-link" style="color: #3598db;" id="videos-tab" data-bs-toggle="tab" data-bs-target="#videos" type="button" role="tab" aria-controls="videos" aria-selected="false">Видео</button>
                    </li>
                    {% endif %}
                  </ul>
          </section>



                    <div class="tab-content" id="myTabContent">

                        {% if object.tech_data %}
                        <div class="tab-pane fade show active" id="technical" role="tabpanel" aria-labelledby="technical-tab">
                          
                          <div class="card mb-3">
                              <div class="card-body d-flex align-items-center">
                                <div class="pl-3 data">
                                  <p class="m-0">{{ object.tech_data|safe }}</p>
                                </div>
                              </div>
                          </div>
                          
                        </div>
                        {% endif %}
                        
                        {% if object.equipmentitemdocument_set.first %}
                        <div class="tab-pane fade" id="documentation" role="tabpanel" aria-labelledby="documentation-tab">
                          {% for document in object.equipmentitemdocument_set.all %}
                            <div class="card mb-3">
                              <a href="{{ document.document.url }}">
                                <div class="card-body d-flex align-items-center">
                                  <div class="icon">
                                    <i class="bi bi-file-pdf" style="font-size: 2rem;"></i>
                                  </div>
                                  <div class="pl-3 data">
                                    <p class="m-0">	{{ document.name }}</p>
                                  </div>
                                </div>
                              </a>
                            </div>
                          {% endfor %}

                        </div>
                        {% endif %}

                        {% if object.equipmentitemyoutubevideourl_set.first %}
                        <div class="tab-pane fade" id="videos" role="tabpanel" aria-labelledby="videos-tab">
                          <div class="card mb-3">
                            {% for video_url in object.equipmentitemyoutubevideourl_set.all %}
                            <div class='embed-container mb-3'><iframe src='{{ video_url.video_url }}' frameborder='0' allowfullscreen></iframe></div>
                            {% endfor %}
                          </div>
                        </div>
                        {% endif %}

                    </div>
                </div>

            </div>

        </div>

      </div>

    </div>
</section>

{% endblock %}
{% block extrascripts %}
<script>
  var swiper = new Swiper('.swiper', {
      direction: 'horizontal',
      loop: true,
      centeredSlides: true,
      autoplay: true,
      simulateTouch:true,

      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
</script>
{% endblock %}