apps/club/urls.py
from django.urls import path

from apps.club.views import ClubMembersView, HistoryAchievementsView

urlpatterns = [
    path("history/", HistoryAchievementsView.as_view(), name="history"),
    path("members/", ClubMembersView.as_view(), name="members"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

DEBUG = settings.DEBUG
MEDIA_URL = settings.MEDIA_URL
MEDIA_ROOT = settings.MEDIA_ROOT

handler400 = "apps.main_page.views.bad_request"
handler403 = "apps.main_page.views.permission_denied"
handler404 = "apps.main_page.views.page_not_found"
handler500 = "apps.main_page.views.server_error"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.main_page.urls")),
    path("", include("apps.club.urls")),
    path("", include("apps.services.urls")),
    path("", include("apps.news.urls")),
    path("", include("apps.projects.urls")),
    path("", include("apps.equipment.urls")),
    path("", include("apps.questions.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

apps/club/models.py
from ckeditor.fields import RichTextField
from django.db import models

from config.utils.youtube_links import get_current_link


class ClubMember(models.Model):
    first_name = models.CharField(
        max_length=50,
        verbose_name="Имя",
    )
    last_name = models.CharField(
        max_length=50,
        verbose_name="Фамилия",
    )
    middle_name = models.CharField(
        max_length=50,
        verbose_name="Отчество",
    )
    vocation = models.CharField(
        max_length=50,
        verbose_name="Должность",
    )
    achievements = models.TextField(
        verbose_name="Достижения",
    )
    image = models.ImageField(
        upload_to="images/club/members/",
        verbose_name="Фотография",
        help_text="Изображения только в формате jpg",
    )
    my_order = models.PositiveIntegerField(
        default=0,
        blank=False,
        null=False,
        verbose_name="Порядок отображения",
    )

    class Meta:
        verbose_name = "Член клуба"
        verbose_name_plural = "Члены клуба"
        ordering = ["my_order"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class HalfStaticPage(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Название страницы",
    )
    slug = models.SlugField(
        unique=True,
        verbose_name="URL страницы",
    )
    text = RichTextField(
        verbose_name="Текст",
    )

    class Meta:
        verbose_name = "Статическая страница"
        verbose_name_plural = "Статические страницы"

    def __str__(self):
        return self.name


class HalfStaticPageImage(models.Model):
    image = models.ImageField(
        upload_to="images/club/staticpages/",
        verbose_name="Изображения для вставки в карусель",
    )
    page = models.ForeignKey(
        HalfStaticPage,
        on_delete=models.CASCADE,
        verbose_name="Статическая страница",
    )
    my_order = models.PositiveIntegerField(
        default=0,
        blank=False,
        null=False,
        verbose_name="Порядок отображения",
    )

    class Meta:
        verbose_name = "Изображение карусели статических страниц"
        verbose_name_plural = "Изображения карусели статических страниц"
        ordering = ["my_order"]

    def __str__(self):
        image_name = (self.image.name).split("/")[-1]
        return image_name


class HalfStaticPageYoutubeVideoUrl(models.Model):
    video_url = models.CharField(
        max_length=150,
        verbose_name="Ссылка на видео YouTube",
    )
    equipment = models.ForeignKey(
        HalfStaticPage,
        on_delete=models.CASCADE,
        verbose_name="Статическая страница",
    )
    my_order = models.PositiveIntegerField(
        default=0,
        blank=False,
        null=False,
        verbose_name="Порядок отображения",
    )

    class Meta:
        verbose_name = "Ссылка на видео YouTube"
        verbose_name_plural = "Ссылки на видео YouTube"
        ordering = ["my_order"]

    def __str__(self):
        self.video_url

    def save(self, *args, **kwargs):
        self.video_url = get_current_link(self.video_url)
        super().save(*args, **kwargs)

apps/club/views.py
from django.views.generic.base import TemplateView

from apps.club.models import ClubMember, HalfStaticPage


class ClubMembersView(TemplateView):

    template_name = "club/members.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["members"] = ClubMember.objects.all()
        return context


class HistoryAchievementsView(TemplateView):

    template_name = "club/history_achievements.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["history"] = HalfStaticPage.objects.get(slug="history")
        return context

templates/club/history_achievements.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ history.name }}{% endblock %}

{% block content %}
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style>
<section>
</section>
<section class="team">
  <div class="container">
    <div class="section-title" data-aos="fade-up">
        <h2>История и Успехи</h2>
    </div>
  </div>
  <div class="container" data-aos="fade-up">
    <div class="row justify-content-center">
      <div class="col-lg-8 col-md-12 col-sm-12">
        <div class="portfolio-details-slider swiper">
          <div class="swiper-wrapper align-items-center">
            {% for image in history.halfstaticpageimage_set.all %}
            <div class="swiper-slide">
              <a href="{{ image.image.url }}" data-gallery="portfolioGallery"
                class="portfolio-lightbox"><img src="{{ image.image.url }}" style="max-width: 100%; max-height: auto; object-position: center;" alt=""></a>
            </div>
            {% endfor %}
          </div>
          <div class="swiper-button-prev" style="color: #d3d3d342"></div>
          <div class="swiper-button-next" style="color: #d3d3d342"></div>
          <div class="swiper-pagination"></div>
        </div>
      </div>
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12">
      <p>
        {{ history.text|safe }}
      </p>
    </div>
    {% if history.halfstaticpageyoutubevideourl_set.first %}
      <div class="row justify-content-center">
        {% for video_url in history.halfstaticpageyoutubevideourl_set.all %}
        <div class="col-lg-6 col-md-12 col-sm-12">
          <div class='embed-container mb-3'><iframe src='{{ video_url.video_url }}' frameborder='0' allowfullscreen></iframe></div>
        </div>
        {% endfor %}
      </div>
    {% endif %}
  </div>
</section>
{% endblock %}
{% block extrascripts %}
<script>
  var swiper = new Swiper('.swiper', {
      direction: 'horizontal',
      loop: true,
      centeredSlides: true,
      autoplay: true,
      simulateTouch:true,

      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
</script>
{% endblock %}

templates/club/members.html
{% extends "base.html" %}
{% load static %}

{% block title %} Наша команда {% endblock %}

{% block content %}
<section></section>
<section id="team" class="team section-bg">
    <div class="container">
    <div class="section-title" data-aos="fade-up">
        <h2>Наша команда</h2>
        <p>Каждый человек в нашей команде ценное звено</p>
    </div>
    <div class="row">
        {% for member in members %}
        <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
        <div class="member" data-aos="fade-up" data-aos-delay="{{ forloop.counter }}00">
            <div class="member-img">
                <a href="{{ member.image.url }}" data-gallery="portfolioGallery"
                class="portfolio-lightbox" title="{{ member.first_name }} {{ member.last_name }}"><img src="{{ member.image.url }}" class="img-fluid" alt=""></a>
            </div>
            <div class="member-info">
            <h4>{{ member.first_name }} {{ member.last_name }}</h4>
            <span>{{ member.vocation }}</span>
            <p>{{ member.achievements }}</p>
            </div>
        </div>
        </div>
        {% endfor %}
    </div>
    </div>
</section>
{% endblock %}

templates/club/performances.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ performances.name }}{% endblock %}

{% block content %}
<section>
</section>
<section class="team">
  <div class="container">
    <div class="section-title" data-aos="fade-up">
        <h2>{{ performances.name }}</h2>
    </div>
  <div class="container" data-aos="fade-up">
    <p>
      {{ performances.text|safe }}
    </p>
  </div>
</section>
{% endblock %}